project:
  type: book
  output-dir: docs

book:
  title: "MAS I"
  author: "Colton Gearhart"
  date: "3/29/24"
  cover-image: mas1.png
  chapters:
    - index.qmd

    - part: partA-prob.qmd
      chapters:
        - ca-prob-0.qmd
        - ca-prob-1.qmd
        - ca-prob-2.qmd
        - ca-prob-3.qmd
        - ca-prob-4.qmd
        - ca-prob-5.qmd
        - ca-prob-6.qmd
        - ca-prob-7.qmd
        - ca-prob-8.qmd
        - ca-prob-quizzes.qmd

    - part: partB-stats.qmd
      chapters:
        - ca-stats.qmd

    - part: partC-glm.qmd
      chapters:
        - islr-2.qmd
        - islr-3.qmd
        - islr-4.qmd
        - islr-5.qmd
        - glm-1.qmd
        - glm-2.qmd
        - glm-3.qmd
        - glm-4.qmd
        - glm-5.qmd
        - ca-glm-4.qmd
        - ca-glm-7.qmd
        - ca-glm-11.qmd
        - ca-glm-misc.qmd
        - ca-glm-quizzes.qmd

format:
  html:
    theme: flatly
    code-link: true
    #code-fold: show
    code-tools: true
    number-depth: 3
    toc-depth: 4
    code-block-border-left: "#2C3E50"
    highlight-style: github
    
title-block-banner: true
